/*
# Restaurant Management Schema

1. New Tables
- `profiles` — extends auth.users with role (admin/caisse/client/livreur), status (pending/active/suspended), phone, full_name
- `dishes` — catalog of all restaurant dishes (name, description, price, category, image_url, is_active)
- `daily_menus` — dishes available on a specific date with quantity_available and quantity_sold
- `orders` — customer orders with order_number, type (sur_place/livraison), status, customer info, totals
- `order_items` — line items within an order (dish snapshot, quantity, unit_price, subtotal)
- `deliveries` — delivery assignments linking orders to delivery personnel
- `reservations` — future table reservations with party size, date, time, status
- `role_codes` — validation codes generated by admin for cashier/delivery account creation

2. Helper Functions
- `get_user_role()` — SECURITY DEFINER, returns the role of the authenticated user
- `validate_role_code(code, role)` — SECURITY DEFINER, checks if a code exists and is unused for a given role
- `consume_role_code(code, role, user_id)` — SECURITY DEFINER, validates and marks a code as used
- `generate_order_number()` — generates a unique CMD-XXXXXX order number
- `handle_new_user()` — trigger function to auto-create a profile on signup

3. Security
- RLS enabled on ALL tables
- Public (anon+authenticated) read access: dishes, daily_menus, orders, order_items, reservations
- Public insert access: orders, order_items, reservations (guests can order without account)
- Staff-only write access: dishes (admin), daily_menus (admin+caisse), orders update (authenticated staff)
- Authenticated-only: profiles (self + admin), deliveries (assigned + admin+caisse), role_codes (admin only)
- Role checks via get_user_role() SECURITY DEFINER function

4. Notes
- Clients can order without an account — anon access is required for orders, order_items, dishes, daily_menus
- Order numbers serve as access keys for guest order tracking
- Admin generates role_codes for cashier/delivery roles; codes are validated at signup
- Profiles auto-created via trigger on auth.users insert
*/

-- ============================================
-- PROFILES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'client' CHECK (role IN ('admin', 'caisse', 'client', 'livreur')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('pending', 'active', 'suspended')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ============================================
-- DISHES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.dishes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  price numeric(10,2) NOT NULL DEFAULT 0,
  category text NOT NULL DEFAULT 'plat' CHECK (category IN ('entree', 'plat', 'dessert', 'boisson')),
  image_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dishes ENABLE ROW LEVEL SECURITY;

-- ============================================
-- DAILY_MENUS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.daily_menus (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dish_id uuid NOT NULL REFERENCES public.dishes(id) ON DELETE CASCADE,
  menu_date date NOT NULL DEFAULT CURRENT_DATE,
  quantity_available integer NOT NULL DEFAULT 0,
  quantity_sold integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(dish_id, menu_date)
);

ALTER TABLE public.daily_menus ENABLE ROW LEVEL SECURITY;

-- ============================================
-- ORDERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number text UNIQUE NOT NULL,
  type text NOT NULL DEFAULT 'sur_place' CHECK (type IN ('sur_place', 'livraison')),
  status text NOT NULL DEFAULT 'en_attente' CHECK (status IN ('en_attente', 'en_preparation', 'pret', 'en_livraison', 'livre', 'paye', 'annule')),
  customer_name text NOT NULL DEFAULT '',
  customer_phone text NOT NULL DEFAULT '',
  customer_email text,
  customer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  table_number text,
  delivery_address text,
  total_amount numeric(10,2) NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'en_attente' CHECK (payment_status IN ('en_attente', 'paye')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- ============================================
-- ORDER_ITEMS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  dish_id uuid REFERENCES public.dishes(id) ON DELETE SET NULL,
  dish_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(10,2) NOT NULL DEFAULT 0,
  subtotal numeric(10,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- ============================================
-- DELIVERIES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  delivery_person_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'assigne' CHECK (status IN ('assigne', 'en_cours', 'livre')),
  assigned_at timestamptz NOT NULL DEFAULT now(),
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;

-- ============================================
-- RESERVATIONS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  customer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  party_size integer NOT NULL DEFAULT 2,
  reservation_date date NOT NULL,
  reservation_time time NOT NULL,
  status text NOT NULL DEFAULT 'en_attente' CHECK (status IN ('en_attente', 'confirmee', 'annulee')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- ============================================
-- ROLE_CODES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.role_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text UNIQUE NOT NULL,
  role text NOT NULL CHECK (role IN ('caisse', 'livreur')),
  used boolean NOT NULL DEFAULT false,
  used_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.role_codes ENABLE ROW LEVEL SECURITY;

-- ============================================
-- HELPER FUNCTIONS (SECURITY DEFINER)
-- ============================================

-- Get the role of the current user
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Get the status of the current user
CREATE OR REPLACE FUNCTION public.get_user_status()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT status FROM public.profiles WHERE id = auth.uid();
$$;

-- Validate a role code (check exists, matches role, and is unused)
CREATE OR REPLACE FUNCTION public.validate_role_code(code_input text, role_input text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.role_codes
    WHERE code = code_input
    AND role = role_input
    AND used = false
  );
$$;

-- Consume a role code (validate + mark as used by a specific user)
CREATE OR REPLACE FUNCTION public.consume_role_code(code_input text, role_input text, user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  code_record record;
BEGIN
  SELECT * INTO code_record FROM public.role_codes
  WHERE code = code_input AND role = role_input AND used = false
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  UPDATE public.role_codes SET used = true, used_by = user_id WHERE id = code_record.id;
  RETURN true;
END;
$$;

-- Generate a unique order number
CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS text
LANGUAGE plpgsql
VOLATILE
SET search_path = public
AS $$
DECLARE
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text;
  exists boolean;
  i int;
BEGIN
  LOOP
    result := 'CMD-';
    FOR i IN 1..6 LOOP
      result := result || substr(chars, floor(random() * 31 + 1)::int, 1);
    END LOOP;
    SELECT EXISTS(SELECT 1 FROM public.orders WHERE order_number = result) INTO exists;
    EXIT WHEN NOT exists;
  END LOOP;
  RETURN result;
END;
$$;

-- Auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone, role, status)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'role', 'client'),
    COALESCE(NEW.raw_user_meta_data->>'status', 'active')
  );
  RETURN NEW;
END;
$$;

-- Trigger for auto-creating profiles
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- RLS POLICIES: PROFILES
-- ============================================

DROP POLICY IF EXISTS "select_own_or_admin_profiles" ON public.profiles;
CREATE POLICY "select_own_or_admin_profiles" ON public.profiles
  FOR SELECT TO authenticated
  USING (auth.uid() = id OR public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "update_own_or_admin_profiles" ON public.profiles;
CREATE POLICY "update_own_or_admin_profiles" ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id OR public.get_user_role() = 'admin')
  WITH CHECK (auth.uid() = id OR public.get_user_role() = 'admin');

-- ============================================
-- RLS POLICIES: DISHES (public catalog)
-- ============================================

DROP POLICY IF EXISTS "select_dishes_public" ON public.dishes;
CREATE POLICY "select_dishes_public" ON public.dishes
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_dishes_admin" ON public.dishes;
CREATE POLICY "insert_dishes_admin" ON public.dishes
  FOR INSERT TO authenticated
  WITH CHECK (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "update_dishes_admin" ON public.dishes;
CREATE POLICY "update_dishes_admin" ON public.dishes
  FOR UPDATE TO authenticated
  USING (public.get_user_role() = 'admin')
  WITH CHECK (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "delete_dishes_admin" ON public.dishes;
CREATE POLICY "delete_dishes_admin" ON public.dishes
  FOR DELETE TO authenticated
  USING (public.get_user_role() = 'admin');

-- ============================================
-- RLS POLICIES: DAILY_MENUS (public read, staff write)
-- ============================================

DROP POLICY IF EXISTS "select_daily_menus_public" ON public.daily_menus;
CREATE POLICY "select_daily_menus_public" ON public.daily_menus
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_daily_menus_staff" ON public.daily_menus;
CREATE POLICY "insert_daily_menus_staff" ON public.daily_menus
  FOR INSERT TO authenticated
  WITH CHECK (public.get_user_role() IN ('admin', 'caisse'));

DROP POLICY IF EXISTS "update_daily_menus_staff" ON public.daily_menus;
CREATE POLICY "update_daily_menus_staff" ON public.daily_menus
  FOR UPDATE TO authenticated
  USING (public.get_user_role() IN ('admin', 'caisse'))
  WITH CHECK (public.get_user_role() IN ('admin', 'caisse'));

DROP POLICY IF EXISTS "delete_daily_menus_staff" ON public.daily_menus;
CREATE POLICY "delete_daily_menus_staff" ON public.daily_menus
  FOR DELETE TO authenticated
  USING (public.get_user_role() IN ('admin', 'caisse'));

-- ============================================
-- RLS POLICIES: ORDERS (public create/track, staff update)
-- ============================================

DROP POLICY IF EXISTS "select_orders_public" ON public.orders;
CREATE POLICY "select_orders_public" ON public.orders
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_orders_public" ON public.orders;
CREATE POLICY "insert_orders_public" ON public.orders
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_orders_staff" ON public.orders;
CREATE POLICY "update_orders_staff" ON public.orders
  FOR UPDATE TO authenticated
  USING (public.get_user_role() IN ('admin', 'caisse', 'livreur'))
  WITH CHECK (public.get_user_role() IN ('admin', 'caisse', 'livreur'));

-- ============================================
-- RLS POLICIES: ORDER_ITEMS (public create/read)
-- ============================================

DROP POLICY IF EXISTS "select_order_items_public" ON public.order_items;
CREATE POLICY "select_order_items_public" ON public.order_items
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_order_items_public" ON public.order_items;
CREATE POLICY "insert_order_items_public" ON public.order_items
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- ============================================
-- RLS POLICIES: DELIVERIES (authenticated only)
-- ============================================

DROP POLICY IF EXISTS "select_deliveries_auth" ON public.deliveries;
CREATE POLICY "select_deliveries_auth" ON public.deliveries
  FOR SELECT TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'caisse')
    OR delivery_person_id = auth.uid()
  );

DROP POLICY IF EXISTS "insert_deliveries_staff" ON public.deliveries;
CREATE POLICY "insert_deliveries_staff" ON public.deliveries
  FOR INSERT TO authenticated
  WITH CHECK (public.get_user_role() IN ('admin', 'caisse'));

DROP POLICY IF EXISTS "update_deliveries_staff" ON public.deliveries;
CREATE POLICY "update_deliveries_staff" ON public.deliveries
  FOR UPDATE TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'caisse')
    OR delivery_person_id = auth.uid()
  )
  WITH CHECK (
    public.get_user_role() IN ('admin', 'caisse')
    OR delivery_person_id = auth.uid()
  );

-- ============================================
-- RLS POLICIES: RESERVATIONS (public create, staff manage)
-- ============================================

DROP POLICY IF EXISTS "select_reservations_public" ON public.reservations;
CREATE POLICY "select_reservations_public" ON public.reservations
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_reservations_public" ON public.reservations;
CREATE POLICY "insert_reservations_public" ON public.reservations
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_reservations_staff" ON public.reservations;
CREATE POLICY "update_reservations_staff" ON public.reservations
  FOR UPDATE TO authenticated
  USING (public.get_user_role() IN ('admin', 'caisse'))
  WITH CHECK (public.get_user_role() IN ('admin', 'caisse'));

-- ============================================
-- RLS POLICIES: ROLE_CODES (admin only)
-- ============================================

DROP POLICY IF EXISTS "select_role_codes_admin" ON public.role_codes;
CREATE POLICY "select_role_codes_admin" ON public.role_codes
  FOR SELECT TO authenticated
  USING (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "insert_role_codes_admin" ON public.role_codes;
CREATE POLICY "insert_role_codes_admin" ON public.role_codes
  FOR INSERT TO authenticated
  WITH CHECK (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "delete_role_codes_admin" ON public.role_codes;
CREATE POLICY "delete_role_codes_admin" ON public.role_codes
  FOR DELETE TO authenticated
  USING (public.get_user_role() = 'admin');

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_daily_menus_date ON public.daily_menus(menu_date);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_type ON public.orders(type);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_order_id ON public.deliveries(order_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_person_id ON public.deliveries(delivery_person_id);
CREATE INDEX IF NOT EXISTS idx_reservations_date ON public.reservations(reservation_date);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

-- ============================================
-- SEED DATA: Sample dishes
-- ============================================
INSERT INTO public.dishes (name, description, price, category, is_active) VALUES
  ('Salade César', 'Laitue romaine, croûtons, parmesan, sauce César', 8.50, 'entree', true),
  ('Soupe à l''oignon', 'Soupe gratinée au fromage', 6.50, 'entree', true),
  ('Carpaccio de Bœuf', 'Fines tranches de bœuf, roquette, parmesan, huile d''olive', 12.00, 'entree', true),
  ('Bœuf Bourguignon', 'Bœuf mijoté au vin rouge, champignons, lardons, pommes de terre', 18.50, 'plat', true),
  ('Poulet Rôti Maison', 'Demi-poulet rôti, légumes de saison, jus de poulet', 15.00, 'plat', true),
  ('Risotto aux Champignons', 'Riz arborio, champignons de Paris, parmesan, beurre', 14.50, 'plat', true),
  ('Pavé de Saumon', 'Saumon grillé, écrasé de pommes de terre, sauce hollandaise', 19.50, 'plat', true),
  ('Burger Gourmet', 'Steak haché, cheddar, bacon, salade, sauce maison, frites', 16.00, 'plat', true),
  ('Tiramisu Maison', 'Mascarpone, café, biscuits savoiardi, cacao', 7.50, 'dessert', true),
  ('Crème Brûlée', 'Crème vanillée, caramel craquant', 6.50, 'dessert', true),
  ('Tarte Tatin', 'Tarte aux pommes caramélisées, glace vanille', 8.00, 'dessert', true),
  ('Coca-Cola 33cl', 'Canette 33cl', 3.00, 'boisson', true),
  ('Eau Minérale 50cl', 'Plate ou pétillante', 2.50, 'boisson', true),
  ('Café Espresso', 'Café italien serré', 2.50, 'boisson', true),
  ('Verre de Vin Rouge', 'Côte du Rhône, verre 15cl', 4.50, 'boisson', true)
ON CONFLICT DO NOTHING;

-- Seed today's daily menu with some dishes
INSERT INTO public.daily_menus (dish_id, menu_date, quantity_available)
SELECT id, CURRENT_DATE, 20 FROM public.dishes WHERE is_active = true
ON CONFLICT (dish_id, menu_date) DO NOTHING;
